### ISSUE TITLE
Distributed Web of Care

### ISSUE THREAD

**Issue by tchoi8** [ournetworks/2018-submissions#13]
# Distributed Web of Care

![](https://dwc-tchoi8.hashbase.io/static/images/og.jpg)

## Description

Distributed Web of Care (DWC) is an initiative to *code to care* and *code carefully*.  Through collaborations with artists, engineers, social scientists and community organizers, DWC imagines distributed networks as a form of interdependence and stewardship, in critical opposition to the networks that dominate the world today. 

Type: [talk | performance ]  
Length: [ 1.5 hour ]  
Additional considerations: [Large indoor space or outdoor space preferred for performance]  

## Session Objective

First part will be a presentation and discussion for 60 minutes. 

The presenter will introduce the '[Uncomputable](http://sfpc.io/uncomputable),' a series of lectures by Alexander R. Galloway and an exhibition by Taeyoon Choi at the School for Poetic Computation in NYC.  

They will also talk about Distributed Web of Care [fellowships](https://dwc-tchoi8.hashbase.io/posts/callforfellows/) and [artists in residences](https://dwc-tchoi8.hashbase.io/posts/air/), as well as the DWC Party planned for the end of July.
 
The presenter will talk about how the word 'care' is important because they think about care as an alternative to control. Care is a soft sense of responsibility and accountability that respects inclusivity and diversity. Without care, everything becomes code. For DWC, code of conduct is as important as the code (software, hardware, protocols and systems). 
 
The presenter will ask "Can we code to care, and can we code carefully? Let’s think about care instead of control. Let’s think about person instead of user. Let’s try and unlearn instead of machine learn."  – More on the [Ethics and Archiving the Web](https://dwc-tchoi8.hashbase.io/posts/eaw/). 

In a group discussion, participants will explore how we can resist the capitalist means of control and instead care for each other through the network. 

Second part will be a collective performance for 30 minutes. Participants will join physical activity using strings and stickers to visualize and embody the distributed network. The group will follow and interpret a structured improvisational choreography.  

![](https://dwc-tchoi8.hashbase.io/static/images/EAW/EAW_35.jpg)

Image: Distributed Web of Care Workshop at the [Ethics and Archiving the Web](http://eaw.rhizome.org), Rhizome/ The New Museum in New York City. 

## Material and Technical Requirements

Video projector or monitor, sound amplification, wireless mic. 

## Presenter(s)
 
Name: Taeyoon Choi
Email: studio@taeyoonchoi.com
Url(s): [taeyoonchoi.com](taeyoonchoi.com)
Twitter: [@tchoi8](http://twitter.com@tchoi8) 
GitHub: [@tchoi8)  

Interested in attending the sprint July 16-18: [Y]  
Interested in a community billet: [host|billet|Y]

## Presenter Bio

Taeyoon Choi is an artist and cofounder of [School for Poetic Computation](http://sfpc.io) and a 2017 - 2018 fellow at the [Data and Society](http://datasociety.org).  

Depending on the funding and schedule, Taeyoon Choi and/ or the Distributed Web of Care fellows may co-present.

**Comment by dcwalk** [comment]
Too bad the timing didn't work out 😢 Hopefully next time!
