### ISSUE TITLE
From Learning To Building Networks

### ISSUE THREAD

**Issue by benhylau** [ournetworks/2018-submissions#4]
# From Learning To Building Networks

_Looking to collaborate with facilitators from other mesh communities on this session. Please leave a comment on this thread if you have experience in network literacy efforts and would like to co-organize this one._

## Description

Share the experience of network literacy efforts undertaken by Toronto Mesh over the past two years, then breakout into facilitated conversations in smaller groups. Explore the following topics and suggest next steps moving forward:

- What are the important topics to cover in a networking workshop and how shall we decide them?
- What outreach and workshop formats lead to long-term engagement and are they inclusive to diverse audiences?
- Comparing a workshop-based approach to more centrally controlled network deployment models, can the former feasibly lead to community network infrastructure that is reliable, sustainable, and equitable?
- What are the friction points preventing workshop participants from taking newly acquired skills to deploy a physical mesh network running peer-to-peer applications?
- What are realistic ways to incentivize knowledge decentralization work and encourage organic spread of literacy around mesh and peer-to-peer technologies?

Type: Discussion/Breakouts/Engaging Session  
Length: 1 hour  
Additional considerations: n/a  

## Session Objective

- Explore a workshop-based approach to building and maintaining community network infrastructure
- Solicit from participants lessons learned and new ideas from their local technical literacy efforts

## Material and Technical Requirements

- Presentation screen
- Whiteboard or similar writing surface
- Space and tables for breakout group discussions

**Comment by dcwalk** [comment]
This is happening during the sprints instead, can see here: https://ournetworks.ca/sprints/
