### ISSUE TITLE
The [terms & conditions of] Exchange

### ISSUE THREAD

**Issue by therealitycorp** [ournetworks/2018-submissions#6]
# The [terms & conditions of] Exchange

## Description

**Designing Privacy** is an ongoing research project and discussion with the aim of furthering the public conversation surrounding digital privacy.

**The [terms & conditions of] Exchange** is one expression of this project, taking the form of a kiosk hosting quick, lighthearted and accessible activities for the public to engage with in order to make tangible the transfer of information that happens in a digital exchange.

These activities include “Test your Endurance” and “Test your Fate”, where participants record personal information during the course of the activity, leading to “The Exchange”, where they exchange this information for a chance to win a prize. _(No personal information is actually collected, participants are asked to shred their own data.)_

Through this project, our goal is to encourage discussion around privacy in the digital landscape through a memorable and accessible experience for the participants.

![The Exchange Kiosk - Constructed](https://user-images.githubusercontent.com/38769004/39399129-55dfba68-4ae6-11e8-8281-e2c225e351ee.jpg)

![The Exchange Kiosk - In Action](https://user-images.githubusercontent.com/38769004/39399130-560064b6-4ae6-11e8-9c29-f4e7438d9561.jpg)

Type: other (experience-based installation) 
Length: N/A 
Additional considerations: We think it will fit well in the Friday night event!

## Session Objective

How can digital exchange be made more tangible?
How can we start a conversation around digital privacy in a lighthearted and approachable way?

## Material and Technical Requirements

This kiosk (including interactions) takes up about 2m x 2m of level floor space.

## Presenters

Name: Department of Unusual Certainties x [Daniel Anthony Rossi] 
Email: sam@douc.ca 
Url(s): [wearedouc.com](http://wearedouc.com), [Daniel’s website] 
Twitter: [@therealitycorp](https://twitter.com/therealitycorp), [@cristoforo_DoUC](https://twitter.com/cristoforo_DoUC) 
Instagram: [@douc_to](https://www.instagram.com/douc_to/), [@danantrosaurus](https://www.instagram.com/danantrosaurus/)
GitHub: @therealitycorp

Interested in attending the sprint July 16-18: N 
Interested in a community billet: N

## Presenter Bio

**Department of Unusual Certainties**
DoUC is a Toronto-based studio who design collaborative processes for engagement, communication and education. In 2010, DoUC started as a result of a shared need to ask questions about our everyday existence. Our work is directed by exploration, information and experimentation that takes shape with a pragmatic approach to solving problems with our clients. We are dedicated to creating substantive content and experiences that people can engage with, reflect on and react to.

**[Daniel Anthony Rossi]**
[Daniel’s bio]

_Note: Will update Daniel's bio & info later this week!_

**Comment by dcwalk** [comment]
Closing this as submissions for the yami-ichi were handle via bit bazaar.
